### ISSUE TITLE
Error on Windows

### ISSUE THREAD

**Issue by radio-satellites** [dbdexter-dev/sdrpp_radiosonde#13]
Hi!

Great software! Unfortunately, I'm getting an error on windows when SDR++ loads with the DLL in the folder.

Can you please help?

73!

Sasha VE3SVF
![image](https://user-images.githubusercontent.com/114111180/217394497-cc367aee-9389-4391-ad9f-869fcbd3396f.png)

**Comment by aero924** [comment]
Yes, I'm getting the exact same error

**Comment by radio-satellites** [comment]
@aero924 I was able to solve it by upgrading to the latest nightly SDR++ build
