### ISSUE TITLE
Radiosonde Decoding Compatibility Table

### ISSUE THREAD

**Issue by LukePrior** [dbdexter-dev/sdrpp_radiosonde#3]
May I suggest including a radiosonde support matrix such as the ones found here: https://github.com/projecthorus/radiosonde_auto_rx#radiosonde-support-matrix
https://github.com/dl9rdz/rdz_ttgo_sonde#radiosonde-support-matrix

I have included an example table but I'm not sure if all the fields are correct

### Radiosonde Support Matrix

Manufacturer | Model | Position | Temperature | Humidity | Pressure
-------------|-------|----------|-------------|----------|----------
Vaisala | RS41-SG/SGP/SGM | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: (for -SGP)
Graw | DFM06/09/17 | :heavy_check_mark: | :heavy_check_mark: | :x: | :x:

**Comment by dbdexter-dev** [comment]
Yep, good point. 

I have included a table in the README. There's one in the repo for the new decoder backend, [sondedump](https://github.com/dbdexter-dev/sondedump), but I guess having one directly in this repo doesn't hurt.
