### ISSUE TITLE
 After the April SDR ++ updates...

### ISSUE THREAD

**Issue by kmp56** [dbdexter-dev/sdrpp_radiosonde#5]
1. After the April SDR ++ updates, the plugin cannot be compiled in
2. It should be:
if (OPT_BUILD_RADIOSONDE_DECODER)
add_subdirectory ("decoder_modules / sdrpp_radiosonde")
endif (OPT_BUILD_RADIOSONDE_DECODER)
- space after endif in the 3rd line ...

Linux, Ubuntu 20.04.4 LTS

**Comment by dbdexter-dev** [comment]
There have been some minor changes to the plugin API, can you confirm that the code on [the dev branch](https://github.com/dbdexter-dev/sdrpp_radiosonde/tree/dev) successfully compiles?

**Comment by kmp56** [comment]
After many attempts, it finally works. Using dev branch downloaded .zip and manually added Sondedump ... 
I also repeated the installation on the laptop - also successfully ...
SOLVED for today ;)
